import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/footer";
import Menu from "@/components/ui/menu";
import { roboto } from "./ui/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`${roboto.className} antialiased`}>
				<div className="mx-auto max-w-screen-lg px-5 sm:px-10">{children}</div>
				<Footer />
				<Menu />
			</body>
		</html>
	);
}
